# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Methods 3 – Fall 2016
email:
description: > # this means to ignore newlines until "baseurl:"
  This website displays student projects from the Design and Urban Ecologies
  Methods 3 class – Fall 2016.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://due-parsons.github.io/methods3-fall2016/" # the base hostname & protocol for your site
twitter_username:
github_username:  DUE-Parsons

# Build settings
markdown: kramdown

# Collections
collections:
  projects:
    author: name
    output: true
    permalink: /projects/:path/
